# Made by perry#1451 on Discord spent about three/four hours researching GitHub actions.
name: Java CI with Gradle.

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Allows access of $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: Gradle wrapper verification
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
          java-package: jdk
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle arguments
        uses: gradle/gradle-build-action@v2
        with:
          # Ensure no Gradle daemons are running anymore when your workflow completes. Creating the cache package might fail due to locks being held by Gradle.
          arguments: |
            setupDecompWorkspace
            build --no-daemon

      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: HitlerHax
          path: build/libs/*-all.jar
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`.
          retention-days: 30 # The retention period must be between 1 and 90 inclusive.
